//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LicenseDataSignature {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LicenseDataSignature() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyApplication.Resources.LicenseDataSignature", typeof(LicenseDataSignature).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;LicenseData&quot;: &quot;ew0KICAiTGljZW5zZUlkIjogMTcsDQogICJDdXN0b21lck5hbWUiOiAiQ3JlYXRpdmUgV29ya3MgU3R1ZGlvIiwNCiAgIlByb2R1Y3ROYW1lIjogIlByb2R1Y3QyIiwNCiAgIlByb2R1Y3RWZXJzaW9uIjogIjEuMCIsDQogICJFeHBpcnlEYXRlIjogIjIwMjUtMTAtMjRUMDA6MDA6MDAiLA0KICAiTm9PZlVzZXJzIjogMSwNCiAgIkZlYXR1cmVzT3JNb2R1bGVzIjogInRlc3QiLA0KICAiQ3VzdG9tZXJQT05vIjogIjEyMyIsDQogICJUYXJnZXRNYWNoaW5lSWRlbnRpdHkiOiAiQjFGQUNBOEYxOThGNUNGOEUxQkJBNDAwOEU4OUU3NkM4MEM4RkVBMUJDNjI0Rjk3RjdGOTJENzdBMjlBRTc2QSIsDQogICJNYWNoaW5lRGVzY3JpcHRpb24iOiAidGVzdCI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseJson {
            get {
                return ResourceManager.GetString("LicenseJson", resourceCulture);
            }
        }
    }
}
